# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-gist, jekyll-paginate, jekyll-sitemap]

# Permalinks
permalink:        pretty

# Setup
title:            skezu'e
tagline:          'And other problems'
description:      'Mechatronics Engineering, Scientific Computing, Arch Linux, Linguistics, and Food'
url:              https://egan.github.io
baseurl:          /

author:
  name:           'Egan McComb'
  url:            https://github.com/egan

paginate:         5

# Custom vars
github:
  repo:           https://github.com/egan/egan.github.io
