# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-gist, jekyll-paginate, jekyll-sitemap]

# Permalinks
permalink:        pretty

# Setup
title:            Needs a Good Title
tagline:          'A Clever Tagline'
description:      'Description'
url:              https://egan.github.io
baseurl:          /

author:
  name:           'Egan McComb'
  url:            https://github.com/egan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/egan/egan.github.io
